# Generated by Django 4.0.3 on 2022-04-02 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Familiar',
            new_name='Familiares',
        ),
    ]
